# -*- coding: utf-8 -*-
"""Student.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8LYy8M5JC7Qdv2osMeoYcKU7elskfo8
"""

run = True

def exit():
  global run
  run = False

def add_student():
  name = input("\n\nEnter the name of the student ")
  marks1 = int(input("\n\nEnter marks of subject 1 "))
  marks2 = int(input("\n\nEnter marks of subject 2 "))
  marks3 = int(input("\n\nEnter marks of subject 3 "))
  
  f = open("student_database.txt","a")
  f.write(name+","+str(marks1)+","+str(marks2)+","+str(marks3)+" \n")
  f.close()

def get_percentage():
  name = input("\n\nEnter the name of the student to get percentage ")
  f = open("student_database.txt","r")
  lines = f.readlines()
  for one_line in lines:
    data = one_line.split(",")
    
    if name == data[0] :
      total = int(data[1]) + int(data[2]) + int(data[3])
      percentage = (total/300)*100
      print("\n\n Student",name,"got a percentage of",percentage,"%")
    f.close()

while run:
  print("The menu is")
  print("1: Add a student")
  print("2: Calculate percentage of a student")
  print("3: Exit")
  
  option = int(input("Enter your option "))
  
  if  option == 1:  
    add_student()
  if  option == 2:
    get_percentage()
  if  option == 3:
    exit()